### ISSUE TITLE
SWADE recharge sound (double sheet sound)

### ISSUE THREAD

**Issue by smoothingplane** [death-save/maestro#110]
**Describe the bug**
When any character recharge their weapon, the sheet sound play doubled

**To Reproduce**
1. Go to weapon not fully charge
2. Click on recharge
4. Ear error

**Expected behavior**
Perhaps no sound or a sheet sound, or rather the possibility of choosing the sound of the charging.

**Foundry Setup (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Foundry Version 0.7.9
 - Maestro Version 0.7.4

**Comment by eclarke12** [comment]
@florad are you able to provide any insight here? :)

**Comment by FloRad** [comment]
I'm not familiar with the module so I have no idea what's going on.

**Comment by eclarke12** [comment]
@smoothingplane what do you mean by "sheet sound"? Do you mean Item Track? Can you please provide some screenshots thank you!

**Comment by eclarke12** [comment]
@salieric is this maybe the thing you are working on?

**Comment by SalieriC** [comment]
@eclarke12 Nah, it's on my module: https://github.com/SalieriC/SWADE-Spices-Flavours
I don't know about this one here, sorry.

**Comment by smoothingplane** [comment]
now it's gone, i'll explain:
when I opened a character sheet or received a notification with "DF Logger" or when a character reloaded the weapon, a sound started like a "sheet being moved" (sorry but I don't know how to explain it better).
I tried to disable some modules, but only when I disabled maestro did the sound not double when recharging, so I thought it was maestro's fault.
I then tried disabling all modules and re-enabling them, and the "sheet" sound doesn't play anymore (for none of the actions).

**Comment by smoothingplane** [comment]
https://user-images.githubusercontent.com/43862671/109397527-4c961b00-7937-11eb-89c3-18beaa6482c0.mp4

**Comment by smoothingplane** [comment]
Ok, I have tried several times and with various settings, the bug happens if:
1. Spices and flavours is active
2. Ammunition management in the system options is active

so it's not a Maestro bug, I don't know why it initially fixed by disabling maestro. Now whether it's disabled or not, nothing changes.
I apologize for not having checked better.

**Comment by SalieriC** [comment]
@smoothingplane this indeed is a problem caused by Spices & Flavours, not Maestro, so @eclarke12 was right. This is because I use the renderCharacterSheet hook to enable the sound. Unfortunately the same hook is used upon updating the sheet. I hope to have that fixed soon. @Ethaks and @eclarke12 had great ideas on how to do it.
In my defense though: I've said in the release that the sound is a bit buggy atm.
Anyway I see you've created [an issue over on the Spices & Flavours repo](https://github.com/SalieriC/SWADE-Spices-Flavours/issues/42) so everything is fine now. This here may be closed now I suppose. Sorry to cause that much trouble over here. ^^'

**Comment by eclarke12** [comment]
Thanks for the info @smoothingplane and @SalieriC !
